services:
  network-deploy-service:
    networks:
      - mybudget

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-kafka-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: dock
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1-local:9092,kafka2-local:9093,kafka3-local:9094

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: dock
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  microservice-db-config:
    extends:
      service: microservice-kafka-config
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-kc:3306/${KC_DB_DATABASE}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${KC_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${KC_DB_PASSWORD}

  microservice-keycloak-config:
    extends:
      service: microservice-db-config
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak-w:7080/realms/mybudget
