services:
  network-deploy-service:
    networks:
      - mybudget

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 768m

  microservice-kafka-config:
    extends:
      service: microservice-base-config
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  microservice-keycloak-config:
    extends:
      service: microservice-db-config
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak-w:8080/realms/mybudget
