services:

  mysql-kc:
    image: mysql:8.0
    container_name: mysql-kc
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ../init/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
      - ../init/accountdb-schema.sql:/docker-entrypoint-initdb.d/accountdb-schema.sql:ro
      - ../init/transactiondb-schema.sql:/docker-entrypoint-initdb.d/transactiondb-schema.sql:ro
    extends:
      file: common-config.yml
      service: microservice-kafka-config

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    extends:
      file: common-config.yml
      service: microservice-kafka-config

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extends:
      file: common-config.yml
      service: microservice-kafka-config

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extends:
      file: common-config.yml
      service: microservice-kafka-config

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extends:
      file: common-config.yml
      service: microservice-kafka-config

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    env_file:
      - .env
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_DATABASE: keycloak
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_SPI_EVENTS_LISTENER_MY_CUSTOM_EVENT_LISTENER_BASE_URL: http://accounts:8080/user
    ports:
      - "7080:8080"
    depends_on:
      mysql-kc:
        condition: service_healthy
    healthcheck:
      test: >-
        wget --spider --quiet http://localhost:8080/realms/master || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: start-dev
    volumes:
      - ./my-providers:/opt/keycloak/providers
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  configserver:
    image: daimyo0/my-budget:configserver
    container_name: configserver
    env_file:
      - configserver-docker.env
    ports:
      - "8071:8071"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --spider --quiet \
            http://localhost:8071/actuator/health/readiness \
            || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: daimyo0/my-budget:eurekaserver
    container_name: eurekaserver
    depends_on:
      configserver:
        condition: service_healthy
    env_file:
      - eurekaserver-docker.env
    ports:
      - "8070:8070"
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --spider --quiet \
            http://localhost:8070/actuator/health/readiness \
            || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      PRING_PROFILES_ACTIVE: "docker"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-base-config

  gatewayserver:
    image: daimyo0/my-budget:gatewayserver
    container_name: gateway
    depends_on:
      transactions:
        condition: service_healthy
      accounts:
        condition: service_healthy
    env_file:
      - gatewayserver-docker.env
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/my-budget/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  accounts:
    image: daimyo0/my-budget:accounts
    container_name: accounts
    env_file:
      - accounts-docker.env
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --spider --quiet \
            http://localhost:8080/actuator/health/readiness \
            || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-kc:3306/accountdb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${KC_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${KC_DB_PASSWORD}
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  transactions:
    image: daimyo0/my-budget:transactions
    container_name: transactions
    env_file:
      - transactions-docker.env
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --spider --quiet \
            http://localhost:8090/actuator/health/readiness \
            || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: transactions
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-kc:3306/transactiondb?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${KC_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${KC_DB_PASSWORD}
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  orchestrator:
    image: daimyo0/my-budget:orchestrator
    container_name: orchestrator
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    env_file:
      - orchestrator-docker.env
    ports:
      - "3333:3333"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  mybudget:
    driver: bridge

volumes:
  mysql_data: 