spring:
  application:
    name: "gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "MyBudget Gateway Server Application"
    version: "0.0.1"

logging:
  level:
    com:
      mybudget:
        gateway: DEBUG

