server:
  port: 8080

spring:
  application:
    name: "accounts"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/my-budget/protocol/openid-connect/certs"
      client:
        registration:
          keycloak:
            client-id: my-budget-ac
            client-secret: 27MKXKTXNCVLIJLazGSDtjNq6WZbOz6H
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            client-name: Keycloak
        provider:
          keycloak:
            authorization-uri: "http://localhost:7080/auth/realms/my-budget/protocol/openid-connect/auth"
            token-uri: "http://localhost:7080/auth/realms/my-budget/protocol/openid-connect/token"
            user-info-uri: "http://localhost:7080/auth/realms/my-budget/protocol/openid-connect/userinfo"
            jwk-set-uri: "http://localhost:7080/auth/realms/my-budget/protocol/openid-connect/certs"

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com:
      mybudget:
        accounts: DEBUG
      netflix.discovery: DEBUG

keycloak:
  realm: my-budget
  resource: my-budget
  auth-server-url: "http://localhost:7080/auth"
  credentials:
    secret: 27MKXKTXNCVLIJLazGSDtjNq6WZbOz6H

  cloud:
    openfeign:
      circuitbreaker:
        enabled=true:

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 2

info:
  app:
    name: "accounts"
    description: "MyBudget Accounts Application"
    version: "0.0.1"
