version: "3.9"

services:
  redis:
    image: redis:7.2
    container_name: redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  mysql-kc:
    image: mysql:8.0.27
    container_name: mysql-kc-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../init/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
      - ../init/accountdb-schema.sql:/docker-entrypoint-initdb.d/accountdb-schema.sql:ro
      - ../init/transactiondb-schema.sql:/docker-entrypoint-initdb.d/transactiondb-schema.sql:ro
    networks:
      - app-network
    healthcheck:
      test:
        [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak-w:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak-w-local
    restart: unless-stopped
    env_file:
      - .env
    command: start-dev
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HOSTNAME: ${KC_HOSTNAME}
    volumes:
      - ./my-providers:/opt/keycloak/providers
    networks:
      - app-network
    depends_on:
      mysql-kc:
        condition: service_healthy
    healthcheck:
      test:
        [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-local
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka1:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka1-local
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092,
        PLAINTEXT_INTERNAL://kafka1-local:29092
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - app-network

  kafka2:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka2-local
    restart: unless-stopped
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9093,
        PLAINTEXT_INTERNAL://kafka2-local:29093
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9093,
        PLAINTEXT_INTERNAL://0.0.0.0:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - zookeeper
      - kafka1
    networks:
      - app-network

  kafka3:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka3-local
    restart: unless-stopped
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9094,
        PLAINTEXT_INTERNAL://kafka3-local:29094
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9094,
        PLAINTEXT_INTERNAL://0.0.0.0:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    depends_on:
      - zookeeper
      - kafka1
    networks:
      - app-network

networks:
  app-network:
