server:
  port: 3333

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: "orchestrator"

  config:
    import: optional:configserver:8071
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
    consumer:
      group-id: "orchestrator-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com:
      mybudget:
        accounts: DEBUG
      netflix.discovery: DEBUG

info:
  app:
    name: "accounts"
    description: "MyBudget Accounts Application"
    version: "0.0.1"
